### ISSUE TITLE
Attempted relative import in non-package

### ISSUE THREAD

**Issue by abate** [VorpalBlade/pelican-cite#2]
while using pelican-cite, python spit back this error. Removing the **.** from author_year solves the problem.

```
Traceback (most recent call last):
  File "/usr/bin/pelican", line 9, in <module>
    load_entry_point('pelican==3.6.3', 'console_scripts', 'pelican')()
  File "/usr/lib/python2.7/dist-packages/pelican/__init__.py", line 386, in main
    pelican, settings = get_instance(args)
  File "/usr/lib/python2.7/dist-packages/pelican/__init__.py", line 380, in get_instance
    return cls(settings), settings
  File "/usr/lib/python2.7/dist-packages/pelican/__init__.py", line 57, in __init__
    self.init_plugins()
  File "/usr/lib/python2.7/dist-packages/pelican/__init__.py", line 77, in init_plugins
    str('module'))
  File "/home/abate/software/lib/pelican-plugins/pelican-cite/pelican_cite.py", line 29, in <module>
    from .author_year import LabelStyle
ValueError: Attempted relative import in non-package
Makefile:67: recipe for target 'html' failed
make: *** [html] Error 1
```

**Comment by cmacmackin** [comment]
Sorry for not responding much much sooner. Under what circumstances do you get this error? I've been able to use Pelican with this plugin and have not gotten the error. It also doesn't make much sense. There is an `__init__.py` file present in the directory, so Python should be able to recognise it as a package. Which version of PybTeX do you have installed? That package seems somewhat unstable and often causes issues with updates.

**Comment by VorpalBlade** [comment]
@abate Is this issue still relevant? I cannot reproduce this.

If it still happens I would be grateful if you could tell me your Python version, version of this project and version of pybtex.

If it doesn't happen it would be nice to be able to close this bug.

**Comment by abate** [comment]
it was a long time ago... I think we can close this bug
